### ISSUE TITLE
Failed to archive friend connection

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/rogerthat-backend#152]
```python
'NoneType' object has no attribute 'archive'
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 318, in post
    self.run_from_request()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 313, in run_from_request
    run(self.request.body)
  File "/base/data/home/apps/s~mobicagecloudhr/49.401108088097998281/add_1_monkey_patches.py", line 283, in _new_deferred_run
    return func(*args, **kwds)
  File "/base/data/home/apps/s~mobicagecloudhr/49.401108088097998281/rogerthat/bizz/profile.py", line 1005, in _archive_friend_connection
    db.run_in_transaction(trans)
  File "/base/data/home/apps/s~mobicagecloudhr/49.401108088097998281/add_1_monkey_patches.py", line 184, in wrapped
    r = run(transaction_guid)
  File "/base/data/home/apps/s~mobicagecloudhr/49.401108088097998281/add_1_monkey_patches.py", line 166, in run
    return _orig_run_in_transaction_options(options, *args, **kwargs)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/api/datastore.py", line 2647, in RunInTransactionOptions
    ok, result = _DoOneTry(function, args, kwargs)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/api/datastore.py", line 2667, in _DoOneTry
    result = function(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/49.401108088097998281/rogerthat/bizz/profile.py", line 998, in trans
    archived_fsic = fsic.archive(FriendServiceIdentityConnectionArchive)
AttributeError: 'NoneType' object has no attribute 'archive'
```

**Comment by RubenMattan** [comment]
Fixed by https://github.com/rogerthat-platform/rogerthat-backend/commit/6c4cb560141679ef29dc85d8b34ba75e6ac27680
