### ISSUE TITLE
Return better error when MFD design is empty

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/rogerthat-backend#193]
Instead of returning 'unknown error'.

To prevent this:
```
0
Unknown exception occurred: error id 4e60f536-3528-452c-929e-e93b0d5eb158
Traceback (most recent call last):
  File "/base/data/home/apps/s~mobicagecloudhr/60.401663256280218441/rogerthat/rpc/service.py", line 558, in _execute_service_api_call
    r = run(f, [], parse_parameters(f, params))
  File "/base/data/home/apps/s~mobicagecloudhr/60.401663256280218441/mcfw/rpc.py", line 180, in run
    result = function(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/60.401663256280218441/rogerthat/rpc/service.py", line 349, in wrapped
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/60.401663256280218441/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/60.401663256280218441/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/60.401663256280218441/rogerthat/service/api/messaging.py", line 374, in start_local_flow
    download_attachments_upfront, push_message, None, flow, flow_params)
  File "/base/data/home/apps/s~mobicagecloudhr/60.401663256280218441/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/60.401663256280218441/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/60.401663256280218441/rogerthat/bizz/service/mfr.py", line 216, in start_local_flow
    must_validate=True)
  File "/base/data/home/apps/s~mobicagecloudhr/60.401663256280218441/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/60.401663256280218441/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/60.401663256280218441/rogerthat/bizz/service/mfd/mfd_javascript.py", line 179, in generate_js_flow
    in _render_flow_definitions(service_user, flow_xml, context, parent_message_key, must_validate).iteritems():
  File "/base/data/home/apps/s~mobicagecloudhr/60.401663256280218441/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/60.401663256280218441/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/60.401663256280218441/rogerthat/bizz/service/mfd/mfd_javascript.py", line 134, in _render_flow_definitions
    validate_message_flow_definition(mf_def, service_user, True)
  File "/base/data/home/apps/s~mobicagecloudhr/60.401663256280218441/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/60.401663256280218441/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/60.401663256280218441/rogerthat/bizz/service/mfd/__init__.py", line 829, in validate_message_flow_definition
    start_vertex = create_json_id(dummy(), "start", "start")
  File "/base/data/home/apps/s~mobicagecloudhr/60.401663256280218441/rogerthat/bizz/service/mfd/__init__.py", line 1348, in create_json_id
    "mfd": str(message_flow_design.key()),
  File "/base/data/home/apps/s~mobicagecloudhr/60.401663256280218441/rogerthat/bizz/service/mfd/__init__.py", line 827, in key
    return db.Key.from_path(MessageFlowDesign.kind(), mfdef.name, parent=parent_key(service_user))
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/api/datastore_types.py", line 522, in from_path
    ValidateString(id_or_name, 'name')
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/api/datastore_types.py", line 181, in ValidateString
    raise exception('%s must not be empty.' % name)
BadValueError: name must not be empty.
```

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-backend#57
