### ISSUE TITLE
Skip the following client errors

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#217]
There are some known issues that are polluting the errors visible at `/mobiadmin/client_errors`

in `rogerthat.bizz.system.shouldLogClientError` ignore these erros 

- Ignore errors with `"mCursorDrawable"` in the `errorMessage` and `"huawei"` in `platformVersion.lower()`

Eg.
```
description: None

errorMessage: java.lang.NoSuchFieldException: No field mCursorDrawable in class Lhuawei/com/android/internal/widget/HwEditor; (declaration of 'huawei.com.android.internal.widget.HwEditor' appears in /system/framework/hwEmui.jar)
	at java.lang.Class.getDeclaredField(Native Method)
	at com.mobicage.rogerthat.util.ui.UIUtils.colorEditText(UIUtils.java:811)
	at com.mobicage.rogerthat.util.ui.UIUtils.setCursorColor(UIUtils.java:833)
	at com.mobicage.rogerthat.util.ui.UIUtils.setColors(UIUtils.java:887)
	at com.mobicage.rogerthat.util.ui.UIUtils.setColors(UIUtils.java:858)
	at com.mobicage.rogerthat.util.ui.UIUtils.setColorsRecursive(UIUtils.java:917)
	at com.mobicage.rogerthat.util.ui.UIUtils.setColorsRecursive(UIUtils.java:919)
	at com.mobicage.rogerthat.util.ui.UIUtils.setColorsRecursive(UIUtils.java:919)
	at com.mobicage.rogerthat.util.ui.UIUtils.setColorsRecursive(UIUtils.java:919)
	at com.mobicage.rogerthat.util.ui.UIUtils.setColorsRecursive(UIUtils.java:919)
	at com.mobicage.rogerthat.util.ui.UIUtils.setColorsRecursive(UIUtils.java:919)
	at com.mobicage.rogerthat.ServiceBoundActivity.setContentView(ServiceBoundActivity.java:526)
	at com.mobicage.rogerthat.NewsActivity.onCreate(NewsActivity.java:100)
	at android.app.Activity.performCreate(Activity.java:6910)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)


mobicageVersion: 0.2842

occurenceCount: 55

platform: 1

platformVersion: HUAWEI/VNS-L31/HWVNS-H:7.0/HUAWEIVNS-L31/C432B380:user/release-keys (-) 24 (-) HUAWEI VNS-L31
```

- Ignore errors with `'Transaction with name "..." took ... milliseconds!'` in the `description`

Eg.
```
description: Bug!
Transaction with name "savePartialNewsItems" took 7232 milliseconds!

errorMessage: java.lang.Exception
	at com.mobicage.rogerthat.util.logging.L.logToServer(L.java:151)
	at com.mobicage.rogerthat.util.logging.L.bug(L.java:114)
	at com.mobicage.rogerthat.util.db.TransactionHelper.runInTransaction(TransactionHelper.java:102)
	at com.mobicage.rogerthat.plugins.news.NewsStore.savePartialNewsItems(NewsStore.java:139)
	at com.mobicage.rogerthat.plugins.news.NewsPlugin.processGetNews(NewsPlugin.java:285)
	at com.mobicage.rogerthat.plugins.news.GetNewsResponseHandler.handle(GetNewsResponseHandler.java:52)
	at com.mobicage.rpc.ResponseReceiverHandler.handle(ResponseReceiverHandler.java:537)
	at com.mobicage.rpc.http.HttpProtocol.process(HttpProtocol.java:253)
	at com.mobicage.rpc.http.HttpProtocol.processIncomingMessagesString(HttpProtocol.java:175)
	at com.mobicage.rpc.http.HttpCommunicator$9$1.safeRun(HttpCommunicator.java:688)
	at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:50)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:168)
	at android.os.HandlerThread.run(HandlerThread.java:61)


mobicageVersion: 0.2847

occurenceCount: 1

platform: 1

platformVersion: htc/tmo_de/htc_m8:6.0/MRA58K/662736.4:user/release-keys (-) 23 (-) HTC One_M8
```

**Comment by RubenMattan** [comment]
I didn't know we had a filter on logging client errors but i prefer that all errors are logged and we filter them by a boolean on the model

**Comment by bart-at-mobicage** [comment]
I like the idea, but in this usecase I wouldn't do this. I would never look at the skipped errors because I already know about them.

In this case the first error must be fixed (https://github.com/rogerthat-platform/rogerthat-android-client/issues/119). I just don't want to see them anymore in the logs.

The 2nd one isn't an error. We should only log it while in the foreground (https://github.com/rogerthat-platform/rogerthat-android-client/issues/181)

**Comment by RubenMattan** [comment]
Well i still want these errors in our history, and you can choose whether or not you want to see them
