### ISSUE TITLE
Failure to build service data

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#226]
Happened with service "Gemeente Hoeilaart" and "Gemeente Berlare"

```
Error while executing getFriend: Traceback (most recent call last): (/base/data/home/apps/e~rogerthat-server/19.402496935029949368/rogerthat/rpc/rpc.py:740)
  File "/base/data/home/apps/e~rogerthat-server/19.402496935029949368/rogerthat/rpc/rpc.py", line 729, in _perform_call
    result[RESULT] = run(function, [], kwargs)
  File "/base/data/home/apps/e~rogerthat-server/19.402496935029949368/mcfw/rpc.py", line 180, in run
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/19.402496935029949368/rogerthat/rpc/rpc.py", line 370, in wrapped
    return f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/19.402496935029949368/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/19.402496935029949368/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/19.402496935029949368/rogerthat/api/friends.py", line 111, in getFriend
    populateFriendResponse()
  File "/base/data/home/apps/e~rogerthat-server/19.402496935029949368/rogerthat/api/friends.py", line 107, in populateFriendResponse
    response.friend = FriendTO.fromDBFriendDetail(friendDetail, True, True, targetUser=user)
  File "/base/data/home/apps/e~rogerthat-server/19.402496935029949368/rogerthat/to/friends.py", line 396, in fromDBFriendDetail
    app_data = service_identity.serviceData.to_json_dict()
  File "/base/data/home/apps/e~rogerthat-server/19.402496935029949368/rogerthat/models/properties/keyvalue.py", line 369, in to_json_dict
    d[k] = self[k]
  File "/base/data/home/apps/e~rogerthat-server/19.402496935029949368/rogerthat/models/properties/keyvalue.py", line 117, in __getitem__
    bucket = self._get_bucket(bucket_id)
  File "/base/data/home/apps/e~rogerthat-server/19.402496935029949368/rogerthat/models/properties/keyvalue.py", line 104, in _get_bucket
    azzert(bucket is not None)
  File "/base/data/home/apps/e~rogerthat-server/19.402496935029949368/mcfw/properties.py", line 52, in azzert
    sorted(sys._getframe(1).f_locals.iteritems()), str(error_message) + '\n  Locals: '))
AssertionError: 
  Locals: 
  - bucket: None
  - bucket_id: 7490002
  - self: <rogerthat.models.properties.keyvalue.KVStore object at 0xf7652cb0>
```

**Comment by bart-at-mobicage** [comment]
Fixed the service data for these services. Looks like a datastore problem.
