### ISSUE TITLE
Backlog stuck because of datastore operation >1MB

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#250]
This error is logged 50+ times

```
Request identity: ***@skynet.be:be-diksmuide (ios) (/base/data/home/apps/e~rogerthat-server/28.403291675810984377/rogerthat/rpc/users.py:145)

Incoming HTTP call from ***@rogerth.at (/base/data/home/apps/e~rogerthat-server/28.403291675810984377/rogerthat/rpc/http.py:81)

Returning BroadcastSettingsFlowCache from cache (/base/data/home/apps/e~rogerthat-server/28.403291675810984377/rogerthat/bizz/service/broadcast.py:532)

Rpc failed, deferring ... <function _store_rpc_api_result_deferred at 0xfa76f7f0> (/base/data/home/apps/e~rogerthat-server/28.403291675810984377/rogerthat/rpc/rpc.py:280)

The value of property "data" is longer than 1048487 bytes. (/base/data/home/apps/e~rogerthat-server/28.403291675810984377/add_1_monkey_patches.py:111)
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/28.403291675810984377/rogerthat/rpc/http.py", line 46, in post
    json_result = process(body)
  File "/base/data/home/apps/e~rogerthat-server/28.403291675810984377/rogerthat/rpc/http.py", line 140, in process
    wait_for_rpcs()
  File "/base/data/home/apps/e~rogerthat-server/28.403291675810984377/rogerthat/rpc/rpc.py", line 355, in wait_for_rpcs
    rpc_items.finalize()
  File "/base/data/home/apps/e~rogerthat-server/28.403291675810984377/rogerthat/rpc/rpc.py", line 282, in finalize
    deferred.defer(defered_func, *args)
  File "/base/data/home/apps/e~rogerthat-server/28.403291675810984377/add_1_monkey_patches.py", line 254, in _new_deferred_defer
    return _old_deferred_defer(f, *args, **kwargs)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 280, in defer
    key = _DeferredTaskEntity(data=pickled).put()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/db/__init__.py", line 1077, in put
    return datastore.Put(self._entity, **kwargs)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/api/datastore.py", line 622, in Put
    return PutAsync(entities, **kwargs).get_result()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
    return self.__get_result_hook(self)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 1893, in __put_hook
    self.check_rpc_success(rpc)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 1385, in check_rpc_success
    raise _ToDatastoreError(err)
BadRequestError: The value of property "data" is longer than 1048487 bytes.

```

**Comment by bart-at-mobicage** [comment]
Reduced the priority because I reduced the size of the `app_data` of that service

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-backend#90
