### ISSUE TITLE
Create FriendNotFoundException for sendMessage and sendForm

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#264]
Raise a `FriendNotFoundException(ServiceApiException)` when sending a message to someone that disabled his/her account.

```
Unknown exception occurred: error id da3482ba-839a-4d94-961b-f89a579f2321 (/base/data/home/apps/e~rogerthat-server/30.403570361730636747/add_1_monkey_patches.py:111)
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/30.403570361730636747/rogerthat/rpc/service.py", line 570, in _execute_service_api_call
    r = run(f, [], parse_parameters(f, params))
  File "/base/data/home/apps/e~rogerthat-server/30.403570361730636747/mcfw/rpc.py", line 180, in run
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/30.403570361730636747/rogerthat/rpc/service.py", line 355, in wrapped
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/30.403570361730636747/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/30.403570361730636747/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/30.403570361730636747/rogerthat/service/api/messaging.py", line 76, in send
    is_mfr=users.get_current_user().is_mfr, broadcast_guid=broadcast_guid, step_id=step_id)
  File "/base/data/home/apps/e~rogerthat-server/30.403570361730636747/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/30.403570361730636747/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/30.403570361730636747/rogerthat/bizz/messaging.py", line 848, in sendMessage
    _validate_members(sender_user_possibly_with_slash_default, sender_is_service_identity, member_users)
  File "/base/data/home/apps/e~rogerthat-server/30.403570361730636747/rogerthat/bizz/messaging.py", line 2901, in _validate_members
    a = are_service_identity_users(members)
  File "/base/data/home/apps/e~rogerthat-server/30.403570361730636747/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/30.403570361730636747/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/30.403570361730636747/rogerthat/dal/profile.py", line 43, in are_service_identity_users
    return [isinstance(p, ServiceIdentity) for p in get_profile_infos(existing_users)]
  File "/base/data/home/apps/e~rogerthat-server/30.403570361730636747/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/30.403570361730636747/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/30.403570361730636747/rogerthat/dal/profile.py", line 224, in get_profile_infos
    azzert(None not in r)
  File "/base/data/home/apps/e~rogerthat-server/30.403570361730636747/mcfw/properties.py", line 52, in azzert
    sorted(sys._getframe(1).f_locals.iteritems()), str(error_message) + '\n  Locals: '))
AssertionError: 
  Locals: 
  - allow_none_in_results: False
  - cache_misses: True
  - expected_types: None
  - f: <function get_service_identity at 0xfafd8a30>
  - i: 0
  - profile_info: None
  - profile_infos: {users.User(email='***@pandora.be:be-sint-truiden'): None}
  - r: [None]
  - remaining_profile_infos: [None]
  - remaining_profile_infos_to_get: [users.User(email='***@pandora.be:be-sint-truiden')]
  - result: <mcfw.consts.MissingClass object at 0xfb98afd0>
  - u: ***:be-sint-truiden
  - update_mem_cache: True
  - update_request_cache: True
  - user: ***@pandora.be:be-sint-truiden
  - users_: [users.User(email='***@pandora.be:be-sint-truiden')]
```

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-backend#89
