### ISSUE TITLE
send_messages_after_registration failed for user with too many messages

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/rogerthat-backend#290]
```
datastore transaction or write too big. (/base/data/home/apps/e~rogerthat-server/41.404124557926031990/add_1_monkey_patches.py:123)
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 318, in post
    self.run_from_request()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 313, in run_from_request
    run(self.request.body)
  File "/base/data/home/apps/e~rogerthat-server/41.404124557926031990/add_1_monkey_patches.py", line 322, in _new_deferred_run
    return func(*args, **kwds)
  File "/base/data/home/apps/e~rogerthat-server/41.404124557926031990/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/41.404124557926031990/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/41.404124557926031990/rogerthat/bizz/messaging.py", line 2611, in send_messages_after_registration
    db.run_in_transaction_options(xg_on, run)
  File "/base/data/home/apps/e~rogerthat-server/41.404124557926031990/add_1_monkey_patches.py", line 211, in wrapped
    r = run(transaction_guid)
  File "/base/data/home/apps/e~rogerthat-server/41.404124557926031990/add_1_monkey_patches.py", line 193, in run
    return _orig_run_in_transaction_options(options, *args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2647, in RunInTransactionOptions
    ok, result = _DoOneTry(function, args, kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2683, in _DoOneTry
    if _GetConnection().commit():
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 2627, in commit
    return rpc.get_result()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
    return self.__get_result_hook(self)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 2688, in __commit_hook
    raise _ToDatastoreError(err)
BadRequestError: datastore transaction or write too big.
```

**Comment by RubenMattan** [comment]
Finalizing transaction items (1448 left)

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-backend#86
