### ISSUE TITLE
Lots of updateMessage requests are failing (ios + android)

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#298]
```
2017-09-25 09:17:10 UTC
   (0 min ago)
***@hotmail.com:be-loc
Count: 1 - Version: 1.2239

description: Error returned as result of client call:
{"a":{"request":{"thread_avatar_hash":null,"message_key":"1b3003f2-7213-453a-85d9-95a64503cabc","thread_background_color":null,"has_flags":false,"parent_message_key":null,"flags":0,"existence":0,"message":null,"thread_text_color":null,"has_existence":true,"last_child_message":null}},"ci":"02f14aab-a1d0-11e7-9eb1-4f45ffd08551","f":"com.mobicage.capi.messaging.updateMessage","t":1506330043,"av":1}

errorMessage: Error while processing incoming call

mobicageVersion: 1.2239

occurenceCount: 1

platform: 7

platformVersion: 
```

```
2017-09-25 09:15:19 UTC
   (2 min ago)
***@skynet.be:be-loc
Count: 1 - Version: 0.2083

description: Error returned as result of client call:
{"a":{"request":{"thread_avatar_hash":null,"message_key":"4531a328-5a5a-48d3-85a5-d2495b96e705","thread_background_color":null,"has_flags":false,"parent_message_key":null,"flags":0,"existence":0,"message":null,"thread_text_color":null,"has_existence":true,"last_child_message":null}},"ci":"fcb8afa3-a1cf-11e7-aa4c-e95a1eab0f87","f":"com.mobicage.capi.messaging.updateMessage","t":1506330032,"av":1}

errorMessage: Error while processing incoming call

mobicageVersion: 0.2083

occurenceCount: 1

platform: 7

platformVersion: 
```

```
2017-09-25 09:14:54 UTC
   (3 min ago)
***@telenet.be:be-loc
Count: 1 - Version: 0.2083

description: Error returned as result of client call:
{"a":{"request":{"thread_avatar_hash":null,"message_key":"ff6c2299-05ce-4d2e-ba1e-2313f93e8a76","thread_background_color":null,"has_flags":false,"parent_message_key":null,"flags":0,"existence":0,"message":null,"thread_text_color":null,"has_existence":true,"last_child_message":null}},"ci":"ff8e3ab5-a1cf-11e7-8cb3-95b38fcbedcb","f":"com.mobicage.capi.messaging.updateMessage","t":1506330037,"av":1}

errorMessage: Error while processing incoming call

mobicageVersion: 0.2083

occurenceCount: 1

platform: 7

platformVersion: 
```

```
2017-09-25 09:13:59 UTC
   (4 min ago)
***@outlook.com:be-loc
Count: 6 - Version: 0.3255

description: None

errorMessage: java.lang.RuntimeException: android.database.sqlite.SQLiteDoneException
	at com.mobicage.rogerthat.util.db.TransactionHelper.runInTransaction(TransactionHelper.java:90)
	at com.mobicage.rogerthat.plugins.messaging.MessageStore.updateMessage(MessageStore.java:681)
	at com.mobicage.rogerthat.plugins.messaging.MessagingPlugin.updateMessage(MessagingPlugin.java:932)
	at com.mobicage.rogerthat.plugins.messaging.MessagingCallReceiver.updateMessage(MessagingCallReceiver.java:470)
	at com.mobicage.rpc.CallReceiver.processCall(CallReceiver.java:135)
	at com.mobicage.rogerthat.plugins.messaging.BrandingMgr$1.safeRun(BrandingMgr.java:805)
	at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:50)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: android.database.sqlite.SQLiteDoneException
	at android.database.sqlite.SQLiteConnection.nativeExecuteForString(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:641)
	at android.database.sqlite.SQLiteSession.executeForString(SQLiteSession.java:685)
	at android.database.sqlite.SQLiteStatement.simpleQueryForString(SQLiteStatement.java:128)
	at com.mobicage.rogerthat.plugins.messaging.MessageStore.lastThreadMessage(MessageStore.java:658)
	at com.mobicage.rogerthat.plugins.messaging.MessageStore.updateSortId(MessageStore.java:662)
	at com.mobicage.rogerthat.plugins.messaging.MessageStore.access$700(MessageStore.java:66)
	at com.mobicage.rogerthat.plugins.messaging.MessageStore$3.run(MessageStore.java:732)
	at com.mobicage.rogerthat.plugins.messaging.MessageStore$3.run(MessageStore.java:681)
	at com.mobicage.rogerthat.util.db.TransactionHelper.runInTransaction(TransactionHelper.java:84)
	... 10 more


mobicageVersion: 0.3255

occurenceCount: 6

platform: 1

platformVersion: Huawei/SCL-L01/hwSCL-Q:5.1.1/HuaweiSCL-L01/C432B150:user/release-keys (-) 22 (-) HUAWEI SCL-L01
```

```
2017-09-25 09:11:09 UTC
   (6 min ago)
***@gmail.com:be-loc
Count: 2 - Version: 1.3407


description: None

errorMessage: java.lang.RuntimeException: android.database.sqlite.SQLiteDoneException
	at com.mobicage.rogerthat.util.db.TransactionHelper.runInTransaction(TransactionHelper.java:90)
	at com.mobicage.rogerthat.plugins.messaging.MessageStore.updateMessage(MessageStore.java:679)
	at com.mobicage.rogerthat.plugins.messaging.MessagingPlugin.updateMessage(MessagingPlugin.java:932)
	at com.mobicage.rogerthat.plugins.messaging.MessagingCallReceiver.updateMessage(MessagingCallReceiver.java:493)
	at com.mobicage.rpc.CallReceiver.processCall(CallReceiver.java:139)
	at com.mobicage.rpc.http.HttpProtocol.process(HttpProtocol.java:226)
	at com.mobicage.rpc.http.HttpProtocol.processIncomingMessagesString(HttpProtocol.java:187)
	at com.mobicage.rpc.http.HttpCommunicator$8$1.safeRun(HttpCommunicator.java:684)
	at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:50)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: android.database.sqlite.SQLiteDoneException
	at android.database.sqlite.SQLiteConnection.nativeExecuteForString(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:711)
	at android.database.sqlite.SQLiteSession.executeForString(SQLiteSession.java:685)
	at android.database.sqlite.SQLiteStatement.simpleQueryForString(SQLiteStatement.java:128)
	at com.mobicage.rogerthat.plugins.messaging.MessageStore.lastThreadMessage(MessageStore.java:656)
	at com.mobicage.rogerthat.plugins.messaging.MessageStore.updateSortId(MessageStore.java:660)
	at com.mobicage.rogerthat.plugins.messaging.MessageStore.access$700(MessageStore.java:66)
	at com.mobicage.rogerthat.plugins.messaging.MessageStore$3.run(MessageStore.java:730)
	at com.mobicage.rogerthat.plugins.messaging.MessageStore$3.run(MessageStore.java:679)
	at com.mobicage.rogerthat.util.db.TransactionHelper.runInTransaction(TransactionHelper.java:84)
	... 12 more


mobicageVersion: 1.3407

occurenceCount: 2

platform: 1

platformVersion: samsung/a3ultexx/a3ulte:6.0.1/MMB29M/A300FUXXS1CQD2:user/release-keys (-) 23 (-) SM-A300FU
```

```
2017-09-25 09:11:07 UTC
   (6 min ago)
***@hotmail.com:be-loc
Count: 1 - Version: 0.3255

description: Error returned as result of client call:
{"a":{"request":{"thread_avatar_hash":null,"message_key":"4c841b4c-59f6-4024-a693-7783c325a92f","thread_background_color":null,"has_flags":false,"parent_message_key":null,"flags":0,"existence":0,"message":null,"thread_text_color":null,"has_existence":true,"last_child_message":null}},"ci":"f851635c-a1cf-11e7-8b44-e95a1eab0f87","f":"com.mobicage.capi.messaging.updateMessage","t":1506330025,"av":1}

errorMessage: android.database.sqlite.SQLiteDoneException
java.lang.RuntimeException: android.database.sqlite.SQLiteDoneException
	at com.mobicage.rogerthat.util.db.TransactionHelper.runInTransaction(TransactionHelper.java:90)
	at com.mobicage.rogerthat.plugins.messaging.MessageStore.updateMessage(MessageStore.java:681)
	at com.mobicage.rogerthat.plugins.messaging.MessagingPlugin.updateMessage(MessagingPlugin.java:932)
	at com.mobicage.rogerthat.plugins.messaging.MessagingCallReceiver.updateMessage(MessagingCallReceiver.java:470)
	at com.mobicage.rpc.CallReceiver.processCall(CallReceiver.java:135)
	at com.mobicage.rpc.http.HttpProtocol.process(HttpProtocol.java:226)
	at com.mobicage.rpc.http.HttpProtocol.processIncomingMessagesString(HttpProtocol.java:187)
	at com.mobicage.rpc.http.HttpCommunicator$8$1.safeRun(HttpCommunicator.java:684)
	at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:50)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: android.database.sqlite.SQLiteDoneException
	at android.database.sqlite.SQLiteConnection.nativeExecuteForString(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:711)
	at android.database.sqlite.SQLiteSession.executeForString(SQLiteSession.java:685)
	at android.database.sqlite.SQLiteStatement.simpleQueryForString(SQLiteStatement.java:128)
	at com.mobicage.rogerthat.plugins.messaging.MessageStore.lastThreadMessage(MessageStore.java:658)
	at com.mobicage.rogerthat.plugins.messaging.MessageStore.updateSortId(MessageStore.java:662)
	at com.mobicage.rogerthat.plugins.messaging.MessageStore.access$700(MessageStore.java:66)
	at com.mobicage.rogerthat.plugins.messaging.MessageStore$3.run(MessageStore.java:732)
	at com.mobicage.rogerthat.plugins.messaging.MessageStore$3.run(MessageStore.java:681)
	at com.mobicage.rogerthat.util.db.TransactionHelper.runInTransaction(TransactionHelper.java:84)
	... 12 more


mobicageVersion: 0.3255

occurenceCount: 1

platform: 4

platformVersion: 
```

and 20 more occurrence for the last 10 minutes.

**Comment by bart-at-mobicage** [comment]
Fixed on iOS: https://github.com/rogerthat-platform/rogerthat-ios-client/commit/160c49d5a9b00c6fbe8b112fcfa15050782e3642

**Comment by bart-at-mobicage** [comment]
Fixed on Android: https://github.com/rogerthat-platform/rogerthat-android-client/commit/1d790750
