### ISSUE TITLE
Problems with news items of deleted services

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#329]
Maybe we can return the UNKNOWN_AVATAR_ID in case the service identity or service profile doesn't exist

news item: `142467004`
sender: `service-36ed398b-1c26-4385-a671-02a6b50c4c46@rogerth.at`

```
Error while executing getNewsItems: Traceback (most recent call last): (/base/data/home/apps/e~rogerthat-server/62.405255973431359661/rogerthat/rpc/rpc.py:740)
  File "/base/data/home/apps/e~rogerthat-server/62.405255973431359661/rogerthat/rpc/rpc.py", line 729, in _perform_call
    result[RESULT] = run(function, [], kwargs)
  File "/base/data/home/apps/e~rogerthat-server/62.405255973431359661/mcfw/rpc.py", line 180, in run
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/62.405255973431359661/rogerthat/rpc/rpc.py", line 370, in wrapped
    return f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/62.405255973431359661/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/62.405255973431359661/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/62.405255973431359661/rogerthat/api/news.py", line 40, in getNewsItems
    return get_news_items_for_user(app_user, request.ids)
  File "/base/data/home/apps/e~rogerthat-server/62.405255973431359661/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/62.405255973431359661/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/62.405255973431359661/rogerthat/bizz/news.py", line 129, in get_news_items_for_user
    missing_news_item_tos = [NewsItemTO.from_model(i, base_url) for i in missing_news_items]
  File "/base/data/home/apps/e~rogerthat-server/62.405255973431359661/rogerthat/to/news.py", line 405, in from_model
    return cls(model.id, si.service_identity_user.email(), si.name, si.avatarId, model.title, model.message,
  File "/base/data/home/apps/e~rogerthat-server/62.405255973431359661/rogerthat/models/__init__.py", line 1134, in avatarId
    return get_service_profile(self.service_user).avatarId
AttributeError: 'NoneType' object has no attribute 'avatarId'
```

```
Queue: default (/base/data/home/apps/e~rogerthat-server/62.405257013364533906/add_1_monkey_patches.py:317)
deferred.run(rogerthat.bizz.log_analysis._analyze,
             1509699720L,
             1509700320)

Summarize: updating 105 news items (/base/data/home/apps/e~rogerthat-server/62.405257013364533906/rogerthat/bizz/log_analysis.py:447)

Failed to execute summarize of 'None'! (/base/data/home/apps/e~rogerthat-server/62.405257013364533906/add_1_monkey_patches.py:125)
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/62.405257013364533906/rogerthat/bizz/log_analysis.py", line 522, in _analyze
    mapping["summarize_func"](mapping["counters"])
  File "/base/data/home/apps/e~rogerthat-server/62.405257013364533906/rogerthat/bizz/log_analysis.py", line 453, in store_news_actions
    to = create_news_item_to(news_item)
  File "/base/data/home/apps/e~rogerthat-server/62.405257013364533906/rogerthat/bizz/log_analysis.py", line 445, in create_news_item_to
    return NewsItemTO.from_model(news_item, server_settings.baseUrl)
  File "/base/data/home/apps/e~rogerthat-server/62.405257013364533906/rogerthat/to/news.py", line 405, in from_model
    return cls(model.id, si.service_identity_user.email(), si.name, si.avatarId, model.title, model.message,
  File "/base/data/home/apps/e~rogerthat-server/62.405257013364533906/rogerthat/models/__init__.py", line 1134, in avatarId
    return get_service_profile(self.service_user).avatarId
AttributeError: 'NoneType' object has no attribute 'avatarId'
```

**Comment by RubenMattan** [comment]
```Error while executing getNews: Traceback (most recent call last): (/base/data/home/apps/e~rogerthat-server/65.405400033571348519/rogerthat/rpc/rpc.py:740)
  File "/base/data/home/apps/e~rogerthat-server/65.405400033571348519/rogerthat/rpc/rpc.py", line 729, in _perform_call
    result[RESULT] = run(function, [], kwargs)
  File "/base/data/home/apps/e~rogerthat-server/65.405400033571348519/mcfw/rpc.py", line 180, in run
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/65.405400033571348519/rogerthat/rpc/rpc.py", line 370, in wrapped
    return f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/65.405400033571348519/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/65.405400033571348519/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/65.405400033571348519/rogerthat/api/news.py", line 31, in getNews
    return get_news_for_user(app_user, request.cursor, request.updated_since)
  File "/base/data/home/apps/e~rogerthat-server/65.405400033571348519/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/65.405400033571348519/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/65.405400033571348519/rogerthat/bizz/news.py", line 92, in get_news_for_user
    to = get_all_news(app_id, cursor, profile, updated_since, _get_connections(get_friends_map(app_user)))
  File "/base/data/home/apps/e~rogerthat-server/65.405400033571348519/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/65.405400033571348519/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/65.405400033571348519/rogerthat/bizz/news.py", line 240, in get_all_news
    if not match_app_id(item.sender, app_id):
  File "/base/data/home/apps/e~rogerthat-server/65.405400033571348519/mcfw/cache.py", line 270, in wrapped
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/65.405400033571348519/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/65.405400033571348519/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/65.405400033571348519/rogerthat/bizz/news.py", line 889, in match_app_id
    return app_id in si.appIds
AttributeError: 'NoneType' object has no attribute 'appIds'
```

**Comment by RubenMattan** [comment]
https://github.com/rogerthat-platform/rogerthat-backend/pull/336
