### ISSUE TITLE
Error in logs when trying to order a sandwich in city-app

### ISSUE THREAD

**Issue by khaledkbadr** [rogerthat-platform/rogerthat-backend#34]
When I order a sandwich in the city app that error appears in the logs, but the `app didn't crash` it completed the order successfully.

```
D/MC: Default response failed for function com.mobicage.api.messaging.jsmfr.newFlowMessage
      java.lang.Exception: 
        Locals: 
        - alert_flags: 1
        - allow_reserved_tag: True
        - attachments: None
        - branding: E1C43A4707DF901F509989AB061750FDFF2AC87A7DF3DA0D5AE5F841F0C64A44
        - broadcast_guid: None
        - broadcast_type: None
        - context: None
        - flags: 352
        - forced_form_result: <rogerthat.models.properties.forms.FormResult object at 0x7fdfbcd22b90>
        - forced_member_status: <rogerthat.to.messaging.MemberStatusTO object at 0x7fdfbcde0950>
        - form: <rogerthat.to.messaging.forms.FormTO object at 0x7fdfbcbce8d0>
        - is_mfr: False
        - key: _js_4f8ea657-cd00-7ebe-2a58-c474d181a6c0
        - member: mohamedk@greenitglobe.com
        - message: What kind of bread would you like?
        - parent_key: None
        - sender_user_possibly_with_slash_default: service-0b835f16-5e04-442c-ab5a-8d5bc83bdc39@rogerth.at/+default+
        - sender_user_without_slash_default: service-0b835f16-5e04-442c-ab5a-8d5bc83bdc39@rogerth.at
        - step_id: message_type
        - tag: __sln__.sandwich_bar
          at com.mobicage.rpc.Response.getResponse(Response.java:51)
          at com.mobicage.rpc.ResponseHandler.handle(ResponseHandler.java:44)
          at com.mobicage.rpc.ResponseReceiverHandler.handle(ResponseReceiverHandler.java:528)
          at com.mobicage.rpc.http.HttpProtocol.process(HttpProtocol.java:253)
          at com.mobicage.rpc.http.HttpProtocol.processIncomingMessagesString(HttpProtocol.java:175)
          at com.mobicage.rpc.http.HttpCommunicator$9$1.safeRun(HttpCommunicator.java:688)
          at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:50)
          at android.os.Handler.handleCallback(Handler.java:739)
          at android.os.Handler.dispatchMessage(Handler.java:95)
          at android.os.Looper.loop(Looper.java:148)
          at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by bart-at-mobicage** [comment]
We would need the server stacktrace to be able to investigate the problem
