### ISSUE TITLE
Chat topic-message sent twice?

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#344]
```
2017-11-24 09:00:38 UTC
   (5 min ago)
***@gmail.com:be-sint-truiden
Count: 1 - Version: 1.3566
```

```
2017-11-24 09:00:35 UTC
   (5 min ago)
***@sint-truiden.be:be-sint-truiden
Count: 1 - Version: 1.3566
```

```
2017-11-24 09:00:31 UTC
   (5 min ago)
***@sint-truiden.be:be-sint-truiden
Count: 1 - Version: 1.3566
```

```
description: Error returned as result of client call:
{"a":{"request":{"message":{"context":null,"members":[],"default_sticky":true,"thread_background_color":null,"threadTimestamp":1511514023284910,"broadcast_type":null,"dismiss_button_ui_flags":0,"key":"eb73d2f1-5197-49a8-9a33-d54ba8c4fdec","message":"{\"i\":[{\"k\":\"Datum\",\"v\":\"24 november 2017 10:00\"}],\"d\":\"*** at gmail.com <***@gmail.com>\",\"t\":\"Stel een vraag\"}","thread_avatar_hash":"61f1b64f264bd668991b97d2ca2f38f5e2e2c683e86148b22290627186a7c4ac","buttons":[],"sender":"service-6490e2f3-4451-46da-aa66-7cca8dfbc76e@rogerth.at","alert_flags":2,"parent_key":null,"thread_text_color":null,"priority":1,"timestamp":1511514022,"flags":31261,"timeout":0,"thread_size":1,"branding":null,"message_type":1,"default_priority":1,"attachments":[]}}},"ci":"ec1182e6-d0f5-11e7-b714-21d9ecccaebb","f":"com.mobicage.capi.messaging.newMessage","t":1511514030,"av":1}

errorMessage: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: message.key (code 1555)
java.lang.RuntimeException: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: message.key (code 1555)
	at com.mobicage.rogerthat.util.db.TransactionHelper.runInTransaction(TransactionHelper.java:90)
	at com.mobicage.rogerthat.util.db.TransactionHelper.runInTransaction(TransactionHelper.java:61)
	at com.mobicage.rogerthat.plugins.messaging.MessageStore.storeNewMessage(MessageStore.java:384)
	at com.mobicage.rogerthat.plugins.messaging.MessagingPlugin.newMessage(MessagingPlugin.java:696)
	at com.mobicage.rogerthat.plugins.messaging.MessagingCallReceiver.newMessage(MessagingCallReceiver.java:113)
	at com.mobicage.rpc.CallReceiver.processCall(CallReceiver.java:85)
	at com.mobicage.rpc.http.HttpProtocol.process(HttpProtocol.java:226)
	at com.mobicage.rpc.http.HttpProtocol.processIncomingMessagesString(HttpProtocol.java:187)
	at com.mobicage.rpc.http.HttpCommunicator$8$1.safeRun(HttpCommunicator.java:684)
	at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:50)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: message.key (code 1555)
	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:553)
	at android.database.sqlite.SQLiteSession.execute(SQLiteSession.java:619)
	at android.database.sqlite.SQLiteStatement.execute(SQLiteStatement.java:44)
	at com.mobicage.rogerthat.plugins.messaging.MessageStore$1.run(MessageStore.java:462)
	at com.mobicage.rogerthat.util.db.TransactionHelper$3.run(TransactionHelper.java:64)
	at com.mobicage.rogerthat.util.db.TransactionHelper.runInTransaction(TransactionHelper.java:84)
	... 13 more


mobicageVersion: 1.3566

occurenceCount: 1

platform: 4

platformVersion: 
```

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-backend#83
