### ISSUE TITLE
NPE in rogerthat.bizz.job.update_friends._prepare_update_friend

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#345]
```
2017-11-21 CET

15:23:22.492
Queue: highload-worker-queue (/base/data/home/apps/e~rogerthat-server/67.405587551156698020/add_1_monkey_patches.py:317)
deferred.run(rogerthat.bizz.job.update_friends._prepare_update_friend,
             users.User(email='***@neerpelt.be:be-neerpelt'),
             datastore_types.Key.from_path(u'mc-tracker', u'***@neerpelt.be:be-neerpelt', u'FriendMap', u'***@neerpelt.be:be-neerpelt', _app=u'e~rogerthat-server'),
             users.User(email='service-ab887b5d-801b-40d3-8183-624a869deceb@rogerth.at/+default+'),
             True)

15:23:22.534
'NoneType' object has no attribute 'user' (/base/data/home/apps/e~rogerthat-server/67.405587551156698020/add_1_monkey_patches.py:123)
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 318, in post
    self.run_from_request()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 313, in run_from_request
    run(self.request.body)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/add_1_monkey_patches.py", line 322, in _new_deferred_run
    return func(*args, **kwds)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/rogerthat/bizz/job/update_friends.py", line 327, in _prepare_update_friend
    run_in_transaction(trans, True)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/rogerthat/utils/transactions.py", line 122, in run_in_transaction
    return run_in_xg_transaction(function, *args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/rogerthat/utils/transactions.py", line 103, in run_in_xg_transaction
    return db.run_in_transaction_options(xg_on, function, *args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/add_1_monkey_patches.py", line 211, in wrapped
    r = run(transaction_guid)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/add_1_monkey_patches.py", line 193, in run
    return _orig_run_in_transaction_options(options, *args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2647, in RunInTransactionOptions
    ok, result = _DoOneTry(function, args, kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2667, in _DoOneTry
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/rogerthat/bizz/job/update_friends.py", line 321, in trans
    get_broadcast_settings_static_flow_hash(profile_info_user, target_user)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/rogerthat/bizz/service/broadcast.py", line 573, in get_broadcast_settings_static_flow_hash
    static_flow = generate_broadcast_settings_static_flow(service_identity_user, app_user)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/rogerthat/bizz/service/broadcast.py", line 556, in generate_broadcast_settings_static_flow
    mfds = generate_broadcast_settings_flow_def(service_identity_user, user_profile)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/rogerthat/bizz/service/broadcast.py", line 414, in generate_broadcast_settings_flow_def
    friend_user = user_profile.user
AttributeError: 'NoneType' object has no attribute 'user'
```

**Comment by bart-at-mobicage** [comment]
This user deactivated his account at Tue 21 Nov 2017 15:22:19 GMT.
Closing. Too minor.
