### ISSUE TITLE
When something goes wrong creating a new user, the system never recovers

### ISSUE THREAD

**Issue by khaledkbadr** [rogerthat-platform/rogerthat-backend#35]
# Problem
Khaled was missing a library for his PIL to work correctly. (Not sure if that's the problem, cause when I reinstalled the app and used new email error still persists)

When a created his user account something went wrong while creating his profile, resulting in the fact that has has no Identity QR code:

```
payload: {"a":"be-loc","p":10,"r":"20284368-b61b-11e6-a781-35e9c97479a4@jabber.mobicage.com","kid":"17f876e4-e733-4008-8b25-984b06e99d4f","t":["xmpp"]}

ESC[1;33mWARNING  2016-11-29 10:04:06,441 system.py:135] getIdentityQRCode ProfilePointer was NoneESC[0m

- request.email: mohamedk@greenitglobe.com
- request.size: None
```

Secondly much more things appear to be wrong with his profile, because you just cannot send any messages to him:
```
ESC[1;31mERROR    2016-11-29 10:12:08,077 add_1_monkey_patches.py:97] send_inbox_forwarders_message chat errorESC[0m

Traceback (most recent call last):
  File "/home/khaled/gig/github/rogerthat/appengine/build/solutions/common/bizz/messaging.py", line 756, in _send_inbox_forwarders_message_by_app
    chat_message_key = messaging.send_chat_message(message.message_key, body, answers, attachments, sender_member, None, True, tag=tag)
  File "/home/khaled/gig/github/rogerthat/appengine/build/rogerthat/rpc/service.py", line 312, in wrapped
    result = f(*args, **kwargs)
  File "/home/khaled/gig/github/rogerthat/appengine/build/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/home/khaled/gig/github/rogerthat/appengine/build/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/home/khaled/gig/github/rogerthat/appengine/build/rogerthat/service/api/messaging.py", line 122, in send_chat_message
    message = bizz_send_chat_message(service_user, parent_key, message, answers, attachments, sender, priority, sticky, tag, alert_flags)
  File "/home/khaled/gig/github/rogerthat/appengine/build/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/home/khaled/gig/github/rogerthat/appengine/build/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/home/khaled/gig/github/rogerthat/appengine/build/rogerthat/bizz/messaging.py", line 1643, in send_chat_message
    priority=priority, default_alert_flags=alert_flags)
  File "/home/khaled/gig/github/rogerthat/appengine/build/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/home/khaled/gig/github/rogerthat/appengine/build/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/home/khaled/gig/github/rogerthat/appengine/build/rogerthat/bizz/messaging.py", line 1144, in sendMessage
    sender=UserDetailsTO.fromUserProfile(profile_info),
  File "/home/khaled/gig/github/rogerthat/appengine/build/rogerthat/to/service.py", line 557, in fromUserProfile
    to.email = get_human_user_from_app_user(user_profile.user).email()
AttributeError: 'NoneType' object has no attribute 'user'

```

# Expected behavior:
- The creation of the profile should be done that it will succeed in any case (try_or_defer ?)
- When reinstalling the app the system should inspect the profile to see if something is lacking

**Comment by khaledkbadr** [comment]
I've reinstalled and reconfigured the platform with no problems in the `PIL` package. But the later problem still persists.
