### ISSUE TITLE
Invalid 'set password' url

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/rogerthat-backend#358]
```
Could not decipher url! (/base/data/home/apps/e~rogerthat-server/flanders2.406211478858914597/add_1_monkey_patches.py:127)
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/flanders2.406211478858914597/rogerthat/pages/login.py", line 108, in parse_and_validate_data
    data, user = self.parse_data(email, data)
  File "/base/data/home/apps/e~rogerthat-server/flanders2.406211478858914597/rogerthat/pages/login.py", line 97, in parse_data
    data = base64.decodestring(data)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_dist/lib/python2.7/base64.py", line 328, in decodestring
    return binascii.a2b_base64(s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 0: ordinal not in range(128)
```

https://github.com/rogerthat-platform/rogerthat-backend/blob/588134a3f812c9ecc5c7c848e7ae0e2678dcf5ea/src/rogerthat/pages/login.py#L95-L101

**Comment by abom** [comment]
This character cannot be in the set password URL, user agent is 

> Mozilla/5.0 (compatible; MJ12bot/v1.4.8; http://mj12bot.com/) 

Should we just log the error in such cases?

**Comment by lucasvanhalst** [comment]
Didn't notice the user agent, guess we can ignore this then
