### ISSUE TITLE
NPE in case app is not found

### ISSUE THREAD

**Issue by abom** [rogerthat-platform/rogerthat-backend#362]
Request:

**GET rogerthat-server.appspot.com/api/1/apple_certs?id=em-be-green-it-globe**

```
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171222t161743.406399471787328240/rogerthat/restapi/admin.py", line 87, in get
    if app.apple_push_cert_valid_until < now() + 30 * DAY:
AttributeError: 'NoneType' object has no attribute 'apple_push_cert_valid_until'
```

Also

```
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/20171222t161743.406399471787328240/mcfw/restapi.py", line 283, in run
    result = run(f, args, kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171222t161743.406399471787328240/mcfw/rpc.py", line 180, in run
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171222t161743.406399471787328240/mcfw/restapi.py", line 93, in wrapped
    return f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171222t161743.406399471787328240/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171222t161743.406399471787328240/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171222t161743.406399471787328240/rogerthat/restapi/apps.py", line 234, in api_get_app_settings
    return AppSettingsTO.from_model(get_app_settings(app_id))
  File "/base/data/home/apps/e~rogerthat-server/20171222t161743.406399471787328240/rogerthat/to/app.py", line 216, in from_model
    return cls(model.wifi_only_downloads, model.background_fetch_timestamps, model.oauth,
AttributeError: 'NoneType' object has no attribute 'wifi_only_downloads'
```

**Comment by bart-at-mobicage** [comment]
Because of app_data migration job there were kicks sent to mobiles of a deleted app.

- [ ] Return status code 404 in this case
- [ ] Implement https://github.com/rogerthat-platform/rogerthat-kickserver/issues/11


I restarted the kick-servers to stop the error log spam
![screen shot 2017-12-29 at 09 48 01](https://user-images.githubusercontent.com/17762105/34433161-a02580de-ec7d-11e7-8165-7336ace18738.png)

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-backend#80
