### ISSUE TITLE
defer arguments in defer_send_app_data_from_db >1Mb

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#369]
```
deferred.defer(_send_set_user_data, target_user, service_identity_user, UpdateUserDataRequestTO.DATA_TYPE_APP,
                   app_data, app_data, skip_mobiles=skip_mobiles, _transactional=db.is_in_transaction(),
                   _queue=get_current_queue() or DEFAULT_QUEUE)
```

`app_data` is greater that 0.5Mb causing the deferred data being longer than 1Mb.

An improvement would be to change the `updated_json_dict` argument in `_send_set_user_data` to `updated_keys`. Then you can construct `updated_json_dict` this way:
```
updated_json_dict = {k: full_json_dict.get(k) for k in updated_keys}
```

However, this way the appData must still be <1Mb so it's not a perfect solution.

Error logs:
```
Queue: default (/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/add_1_monkey_patches.py:322)
deferred.run(rogerthat.bizz.service.defer_send_app_data_from_db,
             users.User(email='***@gmail.com:be-***'),
             users.User(email='service-3eb76ab0-717c-4979-ad5d-5279bfb08eb4@rogerth.at/+default+'))

The value of property "data" is longer than 1048487 bytes. (/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/add_1_monkey_patches.py:125)
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 318, in post
    self.run_from_request()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 313, in run_from_request
    run(self.request.body)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/add_1_monkey_patches.py", line 327, in _new_deferred_run
    return func(*args, **kwds)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/rogerthat/bizz/service/__init__.py", line 2541, in defer_send_app_data_from_db
    _queue=get_current_queue() or DEFAULT_QUEUE)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/add_1_monkey_patches.py", line 298, in _new_deferred_defer
    return _old_deferred_defer(f, *args, **kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 280, in defer
    key = _DeferredTaskEntity(data=pickled).put()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/1/google/appengine/ext/db/__init__.py", line 1077, in put
    return datastore.Put(self._entity, **kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/1/google/appengine/api/datastore.py", line 622, in Put
    return PutAsync(entities, **kwargs).get_result()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
    return self.__get_result_hook(self)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 1893, in __put_hook
    self.check_rpc_success(rpc)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 1385, in check_rpc_success
    raise _ToDatastoreError(err)
BadRequestError: The value of property "data" is longer than 1048487 bytes.
```

**Comment by RubenMattan** [comment]
#377
