### ISSUE TITLE
Failed processing result handler!

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/rogerthat-backend#37]
```python
Result: {u'ci': u'8fc4c163-b75e-11e6-8871-2b31acf6565d', u'r': None, u't': 1480552744, u's': u'success', u'av': 1}
Exception: 'NoneType' object has no attribute 'updated'
Backtrace: Traceback (most recent call last):
  File "/base/data/home/apps/s~mobicagecloudhr/1.397422810290635186/rogerthat/rpc/rpc.py", line 498, in cresult
    result_mapping[rpc_capi_call.resultFunction](context=rpc_capi_call, result=parse_parameter(u"result", result_mapping[rpc_capi_call.resultFunction].meta[u"kwarg_types"][u"result"], result[RESULT]))
  File "/base/data/home/apps/s~mobicagecloudhr/1.397422810290635186/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397422810290635186/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397422810290635186/rogerthat/bizz/friends.py", line 780, in update_friend_response
    if result.updated is False and hasattr(context, 'update_status'):
AttributeError: 'NoneType' object has no attribute 'updated'
```

**Comment by RubenMattan** [comment]
After investigation i notice only iOS users have this issue

**Comment by bart-at-mobicage** [comment]
Already fixed
