### ISSUE TITLE
User not re-connected when scanned by loyalty device

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#370]
- [x] Seems like the put_user_data request failed because the user wasn't (auto-/re-)connected to the service
- [x] In the OFFLOADv1 log entry below, the request_data and response_data shouldn't be null

Happened multiple times. However, it did not happen with my user account when I went to that shop.

```
Queue: default (/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/add_1_monkey_patches.py:322)
deferred.run(solutions.common.bizz.loyalty.update_user_data_user_loyalty,
             users.User(email='keurslagerdebruycker@***.be'),
             u'+default+',
             u'***@fmv-vzw.be',
             u'be-loc',
             1)
```

```
Queue: default (/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/add_1_monkey_patches.py:322)
deferred.run(solutions.common.bizz.loyalty.update_user_data_user_loyalty,
             users.User(email='keurslagerdebruycker@***.be'),
             u'+default+',
             u'***@delaware.pro',
             u'be-loc',
             1)
```

```
Queue: default (/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/add_1_monkey_patches.py:322)
deferred.run(solutions.common.bizz.loyalty.update_user_data_user_loyalty,
             users.User(email='keurslagerdebruycker@skynet.be'),
             u'+default+',
             u'luc.***@telenet.be',
             u'be-loc',
             1)
```

```
Queue: default (/base/data/home/apps/e~rogerthat-server/20171227t161332.406515380053861243/add_1_monkey_patches.py:322)
deferred.run(solutions.common.bizz.loyalty.update_user_data_user_loyalty,
             users.User(email='keurslagerdebruycker@skynet.be'),
             u'+default+',
             u'ria.***@icloud.com',
             u'be-loc',
             1)
```

```
Queue: default (/base/data/home/apps/e~rogerthat-server/20171227t161332.406515380053861243/add_1_monkey_patches.py:322)
deferred.run(solutions.common.bizz.loyalty.update_user_data_user_loyalty,
             users.User(email='keurslagerdebruycker@skynet.be'),
             u'+default+',
             u'ann.***@gmail.com',
             u'be-loc',
             1)
```

```
Queue: default (/base/data/home/apps/e~rogerthat-server/20171227t161332.406515380053861243/add_1_monkey_patches.py:322)
deferred.run(solutions.common.bizz.loyalty.update_user_data_user_loyalty,
             users.User(email='keurslagerdebruycker@skynet.be'),
             u'+default+',
             u'rosita.***@telenet.be',
             u'be-loc',
             1)
```

```
[XX-OFFLOADv1] {"function":"system.put_user_data","request_data":null,"success":false,"timestamp":1514477129,"response_data":null,"type":"api","user":"233d86ac0ff8573c827015235510451b"} (/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/rogerthat/utils/__init__.py:488)

Permanent failure attempting to execute task (/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/add_1_monkey_patches.py:127)
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 318, in post
    self.run_from_request()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 313, in run_from_request
    run(self.request.body)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/add_1_monkey_patches.py", line 327, in _new_deferred_run
    return func(*args, **kwds)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/solutions/common/bizz/loyalty.py", line 249, in update_user_data_user_loyalty
    system.put_user_data(email, json.dumps(user_data), service_identity, app_id)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/rogerthat/rpc/service.py", line 366, in wrapped
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/rogerthat/service/api/system.py", line 322, in put_user_data
    set_user_data(service_identity_user, create_app_user(users.User(email), app_id), user_data)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/rogerthat/bizz/service/__init__.py", line 2610, in set_user_data
    set_user_data_object(service_identity_user, friend_user, data_dict, replace, must_be_friends)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/rogerthat/bizz/service/__init__.py", line 2715, in set_user_data_object
    run_in_xg_transaction(trans, data_dict)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/rogerthat/utils/transactions.py", line 103, in run_in_xg_transaction
    return db.run_in_transaction_options(xg_on, function, *args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/add_1_monkey_patches.py", line 217, in wrapped
    r = run(transaction_guid)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/add_1_monkey_patches.py", line 197, in run
    return _orig_run_in_transaction_options(options, *args, **kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/1/google/appengine/api/datastore.py", line 2647, in RunInTransactionOptions
    ok, result = _DoOneTry(function, args, kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/1/google/appengine/api/datastore.py", line 2667, in _DoOneTry
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/rogerthat/bizz/service/__init__.py", line 2625, in trans
    raise FriendNotFoundException()
FriendNotFoundException: 60011 - User not in friends list - {}
```

**Comment by abom** [comment]
The second point should be fixed by this PR
https://github.com/rogerthat-platform/rogerthat-backend/pull/376

**Comment by abom** [comment]
After following the logs, finally i'm able to reproduce!
The problem happens when a custom loyalty card is used, it's coupled normally, but scanning the same qr code later by the OSA terminal app, then add some loyalty points for example, it gives this error.

![screenshot_2018-01-11-10-45-41](https://user-images.githubusercontent.com/511438/34816133-a27f73f0-f6bc-11e7-93d4-c01180c68f5a.png)

The problem happens if the email entered to a user that's not connected to the service using the same app -it would give the same error if it's e.g. rogerthat app-

_Another note_, the log entry was showing a call to **solutions.vouchers.resolve**, despite the QR code scanned is not a voucher (it's a custom loyalty card), so i think a separate or a common handler to resolve unknown QR codes, would be better and less confusing.

**Comment by bart-at-mobicage** [comment]
Good news that you found the root case. Iirc, when a paper card is initialized, a connection was made between the service and the user. But it looks like this is not happening anymore?

**Comment by abom** [comment]
Don't know for sure, the content of the QR code is not a Rogerthat short URL, but in this case, it's not connected between the service itself with its own app ID (not OSA loyalty app).

**Comment by abom** [comment]
The first point should be fixed by https://github.com/rogerthat-platform/rogerthat-backend/pull/379
