### ISSUE TITLE
"MessageLockedException is not JSON serializable"

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#373]
```
2018-01-03 20:01:56.604 CET
Future is completed: <Future at 0xf2e5b4f0L state=finished raised MessageLockedException> (/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/rogerthat/rpc/rpc.py:318)

2018-01-03 20:01:56.606 CET
Caught exception while executing start_in_new_context callback function (/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/add_1_monkey_patches.py:127)
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/rogerthat/rpc/rpc.py", line 327, in finalize
    err_func(exception)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/rogerthat/rpc/service.py", line 200, in process_error
    json.dumps(call_dict), json.dumps(dict(id=call_dict['id'], result=None, error=error)),
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/add_1_monkey_patches.py", line 257, in _new_json_dumps
    return _orig_json_dumps(*args, **kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_dist/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_dist/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_dist/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_dist/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: MessageLockedException('Message is already locked.',) is not JSON serializable
```

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-backend#79
