### ISSUE TITLE
Failed to load installation logs

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/rogerthat-backend#403]
```python
 (/base/data/home/apps/e~rogerthat-server/20180124t152708.407163991601378018/add_1_monkey_patches.py:127)
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/20180124t152708.407163991601378018/mcfw/restapi.py", line 283, in run
    result = run(f, args, kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180124t152708.407163991601378018/mcfw/rpc.py", line 180, in run
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180124t152708.407163991601378018/mcfw/restapi.py", line 93, in wrapped
    return f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180124t152708.407163991601378018/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180124t152708.407163991601378018/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180124t152708.407163991601378018/rogerthat/pages/admin/installation_logs.py", line 76, in get_installation_logs
    return DeprecatedInstallationsTO.from_model(offset, new_cursor, installations, logs, mobiles, profiles)
  File "/base/data/home/apps/e~rogerthat-server/20180124t152708.407163991601378018/rogerthat/to/installation.py", line 83, in from_model
    logs_per_installation.get(installation.key())))
  File "/base/data/home/apps/e~rogerthat-server/20180124t152708.407163991601378018/rogerthat/to/installation.py", line 65, in from_model
    to = super(DeprecatedInstallationTO, cls).from_model(model, mobile, profile)
  File "/base/data/home/apps/e~rogerthat-server/20180124t152708.407163991601378018/rogerthat/to/installation.py", line 51, in from_model
    platform=model.platform_string,
  File "/base/data/home/apps/e~rogerthat-server/20180124t152708.407163991601378018/rogerthat/models/__init__.py", line 2338, in platform_string
    return Mobile.typeAsString(self.platform)
  File "/base/data/home/apps/e~rogerthat-server/20180124t152708.407163991601378018/rogerthat/rpc/models.py", line 48, in typeAsString
    raise ValueError()
ValueError
```

**Comment by lucasvanhalst** [comment]
already fixed https://github.com/rogerthat-platform/rogerthat-backend/commit/2f00db2dacef491ebc633198662da7d2397cc026#diff-90977c2695269e98ca7aea74755289c2L126
