### ISSUE TITLE
Couldn't follow service via 2nd news feed

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#457]
```
INFO     2018-04-12 15:56:25,710 users.py:145] Request identity: i@foo.com:be-berlare (ios)
INFO     2018-04-12 15:56:25,711 http.py:81] Incoming HTTP call from 4cabe640-3e68-11e8-8c48-a52c75127921@jabber.mobicage.com
INFO     2018-04-12 15:56:25,913 log_offload.py:58] [XX-OFFLOADv1]{"request_data":{"c":[{"ci":"ab17db82-8d5a-4f4d-b9a7-1159cc93ad38","av":1,"a":{"request":{"code":"service-2deae733-7ea1-4b89-afd6-f7856a94660f@rogerth.at","allow_cross_app":false}},"f":"com.mobicage.api.friends.getUserInfo","t":1523548585}],"r":[],"a":[],"av":1},"timestamp":1523548585.913504,"user":"f9287797529002bbf5fdae57631f447b:be-berlare","type":"app","response_data":{"more":false,"r":[{"ci":"ab17db82-8d5a-4f4d-b9a7-1159cc93ad38","r":{"error":{"message":"*****","action":null,"caption":null,"title":"Error"},"avatar":"*****","description":"*****","type":2,"email":"07e74246eaca1a0e415ceb68c20da1d4","profileData":null,"avatar_id":5990689103937536,"name":"Demo Handelaar","descriptionBranding":"0C2C53ADD66C629DDADA9BA4ED856236BBB1ABB9D382A5EC88F7BAB3FD676D56","qualifiedIdentifier":"c19184ecb6d5ab76a86d7ca5dbe780e1","app_id":"be-berlare"},"s":"success","av":1,"t":1523548585}],"ap":"http://192.168.193.66:8080/json-rpc","av":1,"t":1523548585}}
INFO     2018-04-12 15:56:25,914 __init__.py:111] Handling /json-rpc - main_unauthenticated - 0.223s
INFO     2018-04-12 15:56:25,937 module.py:825] default: "POST /json-rpc HTTP/1.1" 200 8424
INFO     2018-04-12 15:56:26,106 __init__.py:474] [XX-SLOGv1] {"_i":"447a230cfc0080c7d707baf6904d2edfde9b","t":1523548586.105967,"T":"Thu, 12 Apr 2018 15:56:26.105","_c":"ZZ","a":{"type_":"user"},"f":"request_identification","e":"i@foo.com:be-berlare","_dc":"us1","_t":123145328189440,"m":"Request identification"}
INFO     2018-04-12 15:56:26,106 users.py:145] Request identity: i@foo.com:be-berlare (ios)
INFO     2018-04-12 15:56:26,107 http.py:81] Incoming HTTP call from 4cabe640-3e68-11e8-8c48-a52c75127921@jabber.mobicage.com
INFO     2018-04-12 15:56:26,186 log_offload.py:58] [XX-OFFLOADv1]{"request_data":{"c":[],"r":[],"a":["ab17db82-8d5a-4f4d-b9a7-1159cc93ad38"],"av":1},"timestamp":1523548586.186855,"user":"f9287797529002bbf5fdae57631f447b:be-berlare","type":"app","response_data":{"more":false,"ap":"http://192.168.193.66:8080/json-rpc","av":1,"t":1523548586}}
INFO     2018-04-12 15:56:26,187 __init__.py:111] Handling /json-rpc - main_unauthenticated - 0.102s
INFO     2018-04-12 15:56:26,204 module.py:825] default: "POST /json-rpc HTTP/1.1" 200 79
INFO     2018-04-12 15:56:29,269 __init__.py:474] [XX-SLOGv1] {"_i":"447a230cfc0080c7d707baf6904d2edfde9b","t":1523548589.269235,"T":"Thu, 12 Apr 2018 15:56:29.269","_c":"ZZ","a":{"type_":"user"},"f":"request_identification","e":"i@foo.com:be-berlare","_dc":"us1","_t":123145328189440,"m":"Request identification"}
INFO     2018-04-12 15:56:29,269 users.py:145] Request identity: i@foo.com:be-berlare (ios)
INFO     2018-04-12 15:56:29,269 http.py:81] Incoming HTTP call from 4cabe640-3e68-11e8-8c48-a52c75127921@jabber.mobicage.com
DEBUG    2018-04-12 15:56:29,286 friends.py:1466] Expected app_id of invitor to be in [be-loc, rogerthat], but was be-berlare
INFO     2018-04-12 15:56:29,322 service.py:222] Starting in new context: flex.friend.invited
{"callback_name":null,"id":"10268ea6-3e6a-11e8-a849-cb1969398dc0","params":{"tag":null,"message":null,"email":"i@foo.com","service_identity":"+default+","origin":"user_invite","language":"en_US","name":"IIIIiiiii","user_details":[{"avatar_url":"http://192.168.193.66:8080/unauthenticated/mobi/cached/avatar/5218557063331840","public_keys":[],"email":"i@foo.com","public_key":null,"language":"en_US","name":"IIIIiiiii","app_id":"be-berlare"}]},"method":"friend.invited"}
INFO     2018-04-12 15:56:29,323 __init__.py:474] [XX-SLOGv1] {"_i":"447a230cfc0080c7d707baf6904d2edfde9b","t":1523548589.323258,"T":"Thu, 12 Apr 2018 15:56:29.323","_c":"ZZ","a":{"message":null,"email":"service-2deae733-7ea1-4b89-afd6-f7856a94660f@rogerth.at"},"f":"com.mobicage.api.friends.invite","e":"i@foo.com:be-berlare","_dc":"us1","_t":123145328189440,"m":"T"}
INFO     2018-04-12 15:56:29,323 __init__.py:474] [XX-SLOGv1] {"_i":"447a230cfc0080c7d707baf6904d2edfde9b","t":1523548589.323606,"T":"Thu, 12 Apr 2018 15:56:29.323","_c":"ZZ","a":{"type_":"user"},"f":"request_identification","e":"service-2deae733-7ea1-4b89-afd6-f7856a94660f@rogerth.at","_dc":"us1","_t":123145332396032,"m":"Request identification"}
INFO     2018-04-12 15:56:29,325 users.py:182] Request identity: service-2deae733-7ea1-4b89-afd6-f7856a94660f@rogerth.at (WEB)
INFO     2018-04-12 15:56:29,349 __init__.py:474] [XX-SLOGv1] {"_i":"447a230cfc0080c7d707baf6904d2edfde9b","t":1523548589.349044,"T":"Thu, 12 Apr 2018 15:56:29.349","_c":"ZZ","a":{"action":"news.followed","news_ids":[77506],"app_id":"be-berlare"},"f":"fti_news","e":"i@foo.com:be-berlare","_dc":"us1","_t":123145328189440,"m":"New follower"}
INFO     2018-04-12 15:56:29,421 log_offload.py:58] [XX-OFFLOADv1]{"request_data":{"c":[{"ci":"8ed676c7-aea7-4b77-84f4-39dfdcbe2442","av":1,"a":{"request":{"message":null,"allow_cross_app":true,"email":"07e74246eaca1a0e415ceb68c20da1d4"}},"f":"com.mobicage.api.friends.invite","t":1523548588},{"ci":"675af86f-5b87-4dd0-b647-d0ca13ce2d65","av":1,"a":{"request":{"news_ids":[77506],"type":"news.followed"}},"f":"com.mobicage.api.news.saveNewsStatistics","t":1523548588}],"r":[],"a":[],"av":1},"timestamp":1523548589.421813,"user":"f9287797529002bbf5fdae57631f447b:be-berlare","type":"app","response_data":{"more":false,"r":[{"ci":"8ed676c7-aea7-4b77-84f4-39dfdcbe2442","r":null,"s":"success","av":1,"t":1523548588},{"ci":"675af86f-5b87-4dd0-b647-d0ca13ce2d65","r":{},"s":"success","av":1,"t":1523548588}],"ap":"http://192.168.193.66:8080/json-rpc","av":1,"t":1523548589}}
INFO     2018-04-12 15:56:29,425 __init__.py:111] Handling /json-rpc - main_unauthenticated - 0.166s
INFO     2018-04-12 15:56:29,426 rpc.py:307] Finalizing futures...
INFO     2018-04-12 15:56:29,426 rpc.py:318] Future is completed: <Future at 0x1133bd350 state=finished returned unicode>
INFO     2018-04-12 15:56:29,433 log_offload.py:58] [XX-OFFLOADv1]{"user":"07e74246eaca1a0e415ceb68c20da1d4","response_data":"accepted","status":true,"type":"callback_api","request_data":{"callback_name":null,"method":"friend.invited","params":{"tag":null,"message":null,"email":"f9287797529002bbf5fdae57631f447b","user_details":[{"avatar_url":"http://192.168.193.66:8080/unauthenticated/mobi/cached/avatar/5218557063331840","public_keys":[],"email":"f9287797529002bbf5fdae57631f447b","public_key":null,"language":"en_US","name":"IIIIiiiii","app_id":"be-berlare"}],"origin":"user_invite","language":"en_US","name":"IIIIiiiii","service_identity":"+default+"},"id":"10268ea6-3e6a-11e8-a849-cb1969398dc0"},"function":"friend.invited","timestamp":1523548589.432975}
INFO     2018-04-12 15:56:29,434 friends.py:484] Storing accepted friend connection from i@foo.com:be-berlare to service-2deae733-7ea1-4b89-afd6-f7856a94660f@rogerth.at/+default+

ERROR    2018-04-12 15:56:29,471 add_1_monkey_patches.py:127] Caught exception while executing start_in_new_context callback function

Traceback (most recent call last):
  File "/Users/bart/mobicage/git/oca-backend/build/rogerthat/rpc/rpc.py", line 323, in finalize
    callback_func(future.result(), *args, **kwargs)
  File "/Users/bart/mobicage/git/oca-backend/build/rogerthat/rpc/service.py", line 196, in process_result
    context=service_api_callback, result=response)
  File "/Users/bart/mobicage/git/oca-backend/build/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/Users/bart/mobicage/git/oca-backend/build/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/Users/bart/mobicage/git/oca-backend/build/rogerthat/bizz/friends.py", line 1188, in invited_response_receiver
    poke, context, message_flow_run_id, user_data)
  File "/Users/bart/mobicage/git/oca-backend/build/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/Users/bart/mobicage/git/oca-backend/build/rogerthat/bizz/friends.py", line 1198, in process_invited_response
    allow_unsupported_apps=allow_unsupported_apps)
  File "/Users/bart/mobicage/git/oca-backend/build/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/Users/bart/mobicage/git/oca-backend/build/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/Users/bart/mobicage/git/oca-backend/build/rogerthat/bizz/friends.py", line 514, in makeFriends
    runMeResult, runHimResult = go() if db.is_in_transaction() else db.run_in_transaction_options(xg_on, go)
  File "/Users/bart/mobicage/git/oca-backend/build/add_1_monkey_patches.py", line 217, in wrapped
    r = run(transaction_guid)
  File "/Users/bart/mobicage/git/oca-backend/build/add_1_monkey_patches.py", line 197, in run
    return _orig_run_in_transaction_options(options, *args, **kwargs)
  File "/Users/bart/Downloads/google-cloud-sdk/platform/google_appengine/google/appengine/api/datastore.py", line 2647, in RunInTransactionOptions
    ok, result = _DoOneTry(function, args, kwargs)
  File "/Users/bart/Downloads/google-cloud-sdk/platform/google_appengine/google/appengine/api/datastore.py", line 2667, in _DoOneTry
    result = function(*args, **kwargs)
  File "/Users/bart/mobicage/git/oca-backend/build/rogerthat/bizz/friends.py", line 502, in go
    "%s and %s can not be friends" % (invitee_profile_info.user, invitor_profile_info.user))
  File "/Users/bart/mobicage/git/oca-backend/build/rogerthat/utils/__init__.py", line 406, in bizz_check
    raise error_class(error_message)
BusinessException: service-2deae733-7ea1-4b89-afd6-f7856a94660f@rogerth.at/+default+ and i@foo.com:be-berlare can not be friends
```

**Comment by RubenMattan** [comment]
As i was investigating this, it turns out the old code or makeFriends is not working properly...

my changes didn't change anything related to make friends (https://github.com/rogerthat-platform/rogerthat-backend/pull/436/files)

**Comment by RubenMattan** [comment]
Shall we debug this on your machine as the code looks good though
