### ISSUE TITLE
Search query error

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#474]
This happens from time to time. But now it occurs more frequently, and almost always in be-herentals

```
Search query error (/base/data/home/apps/e~rogerthat-server/20180424t113917.409246710421677010/add_1_monkey_patches.py:111)
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/20180424t113917.409246710421677010/rogerthat/bizz/service/__init__.py", line 2279, in find_service
    search_result = the_index.search(query)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 102, in positional_wrapper
    return wrapped(*args, **kwds)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/1/google/appengine/api/search/search.py", line 3903, in search
    return self.search_async(query, deadline=deadline, **kwargs).get_result()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/1/google/appengine/api/search/search.py", line 282, in get_result
    return self._get_result_hook()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/1/google/appengine/api/search/search.py", line 3917, in hook
    _CheckStatus(response.status())
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/1/google/appengine/api/search/search.py", line 597, in _CheckStatus
    raise _ERROR_MAP[status.code()](status.error_detail())
InvalidRequest: Failed to execute search request "app_ids:be-herentals action_tags:d2620bdc4c92a0016d714478752aabaf71aa465621c67ed2a217b785726e5435"
```

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-backend#74
