### ISSUE TITLE
Missing params in registration

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#520]
/unauthenticated/mobi/registration/register_device

195.130.155.140 - - [09/Jun/2018:01:39:25 +0200] "POST /unauthenticated/mobi/registration/register_device HTTP/1.1" 500 176 - "Herentals 2.1.2768 (iPad; iOS 11.3.1; nl_BE)" "rogerthat-server.appspot.com" ms=NaN cpu_ms=158 cpm_usd=1.9669e-8 loading_request=0 instance=00c61b117caacaccf854c5916585f15c10b8b71f10d49efc23afab2906797f2d292a0b3974c6 app_engine_release=1.9.54 trace_id=e2d9d9a2a9989b1db681c572e114251e

2018-06-09 01:39:25.727 CEST
UnicodeMultiDict([(u'version', u'3'), (u'', u''), (u'registration_time', u'1528313861'), (u'device_id', u'B8DB271C-56D9-428E-9E83-75D4569040B8'), (u'registration_id', u'5b8e10c1-8453-44b1-987f-6e9df011699a'), (u'tos_age', u'16+'), (u'signature', u'***'), (u'language', u'nl'), (u'country', u'BE'), (u'app_id', u'be-herentals'), (u'use_xmpp_kick', u'false'), (u'hardware_model', u'iPad Pro 10.5-inch (Cellular)'), (u'sim_carrier_name', u'Carrier')]) (/base/data/home/apps/e~rogerthat-server/20180608t091910.410288129468509991/rogerthat/pages/register_mobile.py:781)

2018-06-09 01:39:25.728 CEST
```
coercing to Unicode: need string or buffer, NoneType found (/base/data/home/apps/e~rogerthat-server/20180608t091910.410288129468509991/add_1_monkey_patches.py:128)
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180608t091910.410288129468509991/rogerthat/pages/register_mobile.py", line 801, in post
    registration_id + " " + base64.b64decode(server_settings.registrationMainSignature.encode("utf8")))
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-backend#59
