### ISSUE TITLE
Do nothing in ackInvitation for deactivated users

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#533]
One of the users was deactivated. In that case we should error, but just do nothing in ackInvitation or makeFriends.

```
2018-06-22 10:50:25.835 CEST
Queue: default
deferred.run(rogerthat.bizz.friends.ackInvitation,
             <rogerthat.models.Message object at 0x2ab26cf86e10>)

2018-06-22 10:50:25.835 CEST
Storing accepted friend connection from ***@hotmail.com:be-zulte to ***@hotmail.com:be-zulte

2018-06-22 10:50:25.922 CEST
  Locals: 
  - allow_none_in_results: False
  - cache_key: v1.X2dldF9wcm9maWxlLnJvZ2VydGhhdC5kYWwucHJvZmlsZTExMSQAAABqb2xpZW52YW5yZWNoZW1AaG90bWFpbC5jb206YmUtenVsdGU=
  - cache_misses: True
  - expected_types: None
  - f: <function _get_profile at 0x2ab268a11320>
  - i: 1
  - profile_info: None
  - profile_infos: {users.User(email='***@hotmail.com:be-zulte'): None,
 users.User(email='***@hotmail.com:be-zulte'): <rogerthat.models.FacebookUserProfile object at 0x2ab26c0f2750>}
  - r: [<rogerthat.models.FacebookUserProfile object at 0x2ab26c0f2750>, None]
  - remaining_profile_infos: [<rogerthat.models.FacebookUserProfile object at 0x2ab26c0f2750>, None]
  - remaining_profile_infos_to_get: [users.User(email='***@hotmail.com:be-zulte'),
 users.User(email='***@hotmail.com:be-zulte')]
  - result: <mcfw.consts.MissingClass object at 0x2ab26839dc10>
  - u: ***@hotmail.com:be-zulte
  - update_mem_cache: True
  - update_request_cache: True
  - user: ***@hotmail.com:be-zulte
  - users_: [users.User(email='***@hotmail.com:be-zulte'),
 users.User(email='***@hotmail.com:be-zulte')]
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/be731db3a3e23b1a/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/be731db3a3e23b1a/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/be731db3a3e23b1a/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/be731db3a3e23b1a/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/be731db3a3e23b1a/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/be731db3a3e23b1a/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/be731db3a3e23b1a/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 318, in post
    self.run_from_request()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/be731db3a3e23b1a/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 313, in run_from_request
    run(self.request.body)
  File "/base/data/home/apps/e~rogerthat-server/20180621t141338.410594391782748993/add_1_monkey_patches.py", line 351, in _new_deferred_run
    return func(*args, **kwds)
  File "/base/data/home/apps/e~rogerthat-server/20180621t141338.410594391782748993/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180621t141338.410594391782748993/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180621t141338.410594391782748993/rogerthat/bizz/friends.py", line 618, in ackInvitation
    makeFriends(invitor, invitee, invitee, servicetag, origin=origin)
  File "/base/data/home/apps/e~rogerthat-server/20180621t141338.410594391782748993/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180621t141338.410594391782748993/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180621t141338.410594391782748993/rogerthat/bizz/friends.py", line 485, in makeFriends
    invitee_profile_info, invitor_profile_info = get_profile_infos([invitee, invitor])
  File "/base/data/home/apps/e~rogerthat-server/20180621t141338.410594391782748993/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180621t141338.410594391782748993/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180621t141338.410594391782748993/rogerthat/dal/profile.py", line 237, in get_profile_infos
    azzert(None not in r)
  File "/base/data/home/apps/e~rogerthat-server/20180621t141338.410594391782748993/mcfw/properties.py", line 52, in azzert
    sorted(sys._getframe(1).f_locals.iteritems()), str(error_message) + '\n  Locals: '))
AssertionError: 
  Locals: 
  - allow_none_in_results: False
  - cache_key: v1.X2dldF9wcm9maWxlLnJvZ2VydGhhdC5kYWwucHJvZmlsZTExMSQAAABqb2xpZW52YW5yZWNoZW1AaG90bWFpbC5jb206YmUtenVsdGU=
  - cache_misses: True
  - expected_types: None
  - f: <function _get_profile at 0x2ab268a11320>
  - i: 1
  - profile_info: None
  - profile_infos: {users.User(email='***@hotmail.com:be-zulte'): None,
 users.User(email='***@hotmail.com:be-zulte'): <rogerthat.models.FacebookUserProfile object at 0x2ab26c0f2750>}
  - r: [<rogerthat.models.FacebookUserProfile object at 0x2ab26c0f2750>, None]
  - remaining_profile_infos: [<rogerthat.models.FacebookUserProfile object at 0x2ab26c0f2750>, None]
  - remaining_profile_infos_to_get: [users.User(email='***@hotmail.com:be-zulte'),
 users.User(email='***@hotmail.com:be-zulte')]
  - result: <mcfw.consts.MissingClass object at 0x2ab26839dc10>
  - u: ***@hotmail.com:be-zulte
  - update_mem_cache: True
  - update_request_cache: True
  - user: ***@hotmail.com:be-zulte
  - users_: [users.User(email='***@hotmail.com:be-zulte'),
 users.User(email='***@hotmail.com:be-zulte')]
```

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-backend#70
