### ISSUE TITLE
'NoneType' object has no attribute 'disabled_broadcast_types'

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#542]
```
2018-06-28 04:03:50.767 CEST
X-Appengine-Taskretrycount:9, X-Appengine-Tasketa:1530151430.5572419, X-Appengine-Taskpreviousresponse:500, X-Appengine-Taskretryreason:App Error, X-Appengine-Current-Namespace:, X-Appengine-Taskname:0649100278273740787, X-Appengine-Taskexecutioncount:9, X-Appengine-Queuename:highload-worker-queue, X-Appengine-Country:ZZ

2018-06-28 04:03:50.768 CEST
Queue: highload-worker-queue
deferred.run(rogerthat.bizz.job.update_friends._update_friend,
             datastore_types.Key.from_path(u'mc-tracker', u'roel@mobicage.com:be-loc', u'FriendMap', u'roel@mobicage.com:be-loc', _app=u'e~rogerthat-server'),
             <rogerthat.bizz.friend_helper._FriendCloudStorageHelper object at 0x2b130874db50>,
             False)

2018-06-28 04:03:51.100 CEST
'NoneType' object has no attribute 'disabled_broadcast_types'
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 318, in post
    self.run_from_request()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 313, in run_from_request
    run(self.request.body)
  File "/base/data/home/apps/e~rogerthat-server/20180627t163645.410735841167019158/add_1_monkey_patches.py", line 351, in _new_deferred_run
    return func(*args, **kwds)
  File "/base/data/home/apps/e~rogerthat-server/20180627t163645.410735841167019158/rogerthat/bizz/job/update_friends.py", line 347, in _update_friend
    run_in_transaction(trans, True)
  File "/base/data/home/apps/e~rogerthat-server/20180627t163645.410735841167019158/rogerthat/utils/transactions.py", line 122, in run_in_transaction
    return run_in_xg_transaction(function, *args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180627t163645.410735841167019158/rogerthat/utils/transactions.py", line 103, in run_in_xg_transaction
    return db.run_in_transaction_options(xg_on, function, *args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180627t163645.410735841167019158/add_1_monkey_patches.py", line 222, in wrapped
    r = run(transaction_guid)
  File "/base/data/home/apps/e~rogerthat-server/20180627t163645.410735841167019158/add_1_monkey_patches.py", line 202, in run
    return _orig_run_in_transaction_options(options, *args, **kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2635, in RunInTransactionOptions
    function, *args, **kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2710, in _RunInTransactionInternal
    ok, result = _DoOneTry(function, args, kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2748, in _DoOneTry
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180627t163645.410735841167019158/rogerthat/bizz/job/update_friends.py", line 309, in trans
    if getattr(fsic, attr) is None:
AttributeError: 'NoneType' object has no attribute 'disabled_broadcast_types'
```

```
2018-06-28 04:03:57.184 CEST
X-Appengine-Taskretrycount:9, X-Appengine-Tasketa:1530151437.07543, X-Appengine-Taskpreviousresponse:500, X-Appengine-Taskretryreason:App Error, X-Appengine-Current-Namespace:, X-Appengine-Taskname:8203944459413944041, X-Appengine-Taskexecutioncount:9, X-Appengine-Queuename:highload-worker-queue, X-Appengine-Country:ZZ

2018-06-28 04:03:57.185 CEST
Queue: highload-worker-queue
deferred.run(rogerthat.bizz.job.update_friends._update_friend,
             datastore_types.Key.from_path(u'mc-tracker', u'sven@***:be-beveren', u'FriendMap', u'sven@***:be-beveren', _app=u'e~rogerthat-server'),
             <rogerthat.bizz.friend_helper._FriendCloudStorageHelper object at 0x2b14d2197050>,
             False)

2018-06-28 04:03:58.262 CEST
'NoneType' object has no attribute 'disabled_broadcast_types'
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 318, in post
    self.run_from_request()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 313, in run_from_request
    run(self.request.body)
  File "/base/data/home/apps/e~rogerthat-server/20180627t163645.410735841167019158/add_1_monkey_patches.py", line 351, in _new_deferred_run
    return func(*args, **kwds)
  File "/base/data/home/apps/e~rogerthat-server/20180627t163645.410735841167019158/rogerthat/bizz/job/update_friends.py", line 347, in _update_friend
    run_in_transaction(trans, True)
  File "/base/data/home/apps/e~rogerthat-server/20180627t163645.410735841167019158/rogerthat/utils/transactions.py", line 122, in run_in_transaction
    return run_in_xg_transaction(function, *args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180627t163645.410735841167019158/rogerthat/utils/transactions.py", line 103, in run_in_xg_transaction
    return db.run_in_transaction_options(xg_on, function, *args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180627t163645.410735841167019158/add_1_monkey_patches.py", line 222, in wrapped
    r = run(transaction_guid)
  File "/base/data/home/apps/e~rogerthat-server/20180627t163645.410735841167019158/add_1_monkey_patches.py", line 202, in run
    return _orig_run_in_transaction_options(options, *args, **kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2635, in RunInTransactionOptions
    function, *args, **kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2710, in _RunInTransactionInternal
    ok, result = _DoOneTry(function, args, kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2748, in _DoOneTry
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180627t163645.410735841167019158/rogerthat/bizz/job/update_friends.py", line 309, in trans
    if getattr(fsic, attr) is None:
AttributeError: 'NoneType' object has no attribute 'disabled_broadcast_types'
```

**Comment by lucasvanhalst** [comment]
fixed for these 2 users, was due to an old bug from the past
