### ISSUE TITLE
news.delete should not raise a NewsNotFoundException

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#89]
Instead of throwing a NewsNotFoundException, news.delete should return a boolean to indicate wether or not the news item existed when trying to delete. Deleting something using the api should never raise an exception if it was not found, because the goal is reached: the item is not there anymore.

Delete the class NewsNotFoundException and refactor the code that expected this exception.

```
09:42:58.158
[XX-OFFLOADv1] {"function":"news.delete","request_data":{"news_id":50907003},"success":false,"timestamp":1486456978,"response_data":null,"type":"api","user":"fc366973d34ce79fc39af12bf2f8d70a"}

09:42:58.161
90001 - News with id 50907003 not found - {}
Traceback (most recent call last):
  File "/base/data/home/apps/s~mobicagecloudhr/9.399000778755475790/solutions/common/restapi/news.py", line 103, in rest_delete_news
    delete_news(news_id)
  File "/base/data/home/apps/s~mobicagecloudhr/9.399000778755475790/solutions/common/bizz/news.py", line 368, in delete_news
    news.delete(news_id)
  File "/base/data/home/apps/s~mobicagecloudhr/9.399000778755475790/rogerthat/rpc/service.py", line 337, in wrapped
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/9.399000778755475790/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/9.399000778755475790/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/9.399000778755475790/rogerthat/service/api/news.py", line 92, in delete
    news.delete(news_id, service_identity_user)
  File "/base/data/home/apps/s~mobicagecloudhr/9.399000778755475790/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/9.399000778755475790/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/9.399000778755475790/rogerthat/bizz/news.py", line 764, in delete
    news_item = _get_and_validate_news_item(news_id, service_identity_user)
  File "/base/data/home/apps/s~mobicagecloudhr/9.399000778755475790/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/9.399000778755475790/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/9.399000778755475790/rogerthat/bizz/news.py", line 671, in _get_and_validate_news_item
    raise NewsNotFoundException(news_id)
NewsNotFoundException: 90001 - News with id 50907003 not found - {}

09:42:58.169
[XX-OFFLOADv1] {"function":"/common/news/delete","request_data":{"news_id":50907003},"success":true,"timestamp":1486456978,"response_data":{"errormsg":null,"success":false},"type":"web","user":"fc366973d34ce79fc39af12bf2f8d70a"}
```

**Comment by abom** [comment]
_get_and_validate_news_item() raises NewsNotFoundException, but it's used in other places other than news.delete(), like news.get_news().

Should we keep the NewsNotFoundException and just ignore it in news.delete()?

**Comment by bart-at-mobicage** [comment]
Ok, let's keep it in news.get_news
